# flake8: noqa
from typing import Tuple, Sequence, Union, Optional

class Image:
    def __init__(self) -> None: ...
    def putpalette(self, data: Sequence[int]) -> None: ...
    def save(self, fp: str) -> None: ...
    def rotate(self, angle: Union[int, float]) -> Image: ...

def new(mode: str, size: Tuple[int, int], color: Optional[int] = 0) -> Image: ...
def open(fp: str) -> Image: ...
